### ISSUE TITLE
Index out of range referencing: cellblender.simulation_popen_list[index]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mcellteam/cellblender#72]
```
There might be a problem with the simulation_popen_list code in v1.0RC3

 ( CellBlenderID = a6a38d85b6a1efb362dba46b3b07f944a49948ed )

I'm not sure about the source of the problem, but when opening previously saved 
blend files I sometimes get a series of messages saying that:

  cellblender.simulation_popen_list[index]

produces an "index out of range" error. I can only speculate that the list 
contains some dynamic components that are not saved in the blend file?

Here are the messages:

cellblender@rufus:~$ Traceback (most recent call last):
  File "/home/cellblender/.config/blender/2.71/scripts/addons/cellblender/cellblender_panels.py", line 171, in draw_item
    sp = cellblender.simulation_popen_list[index]
IndexError: list index out of range

location: 
/home/cellblender/.config/blender/2.71/scripts/addons/cellblender/cellblender_pa
nels.py:263

location: 
/home/cellblender/.config/blender/2.71/scripts/addons/cellblender/cellblender_pa
nels.py:263
Traceback (most recent call last):
  File "/home/cellblender/.config/blender/2.71/scripts/addons/cellblender/cellblender_panels.py", line 171, in draw_item
    sp = cellblender.simulation_popen_list[index]
IndexError: list index out of range

location: 
/home/cellblender/.config/blender/2.71/scripts/addons/cellblender/cellblender_pa
nels.py:263

location: 
/home/cellblender/.config/blender/2.71/scripts/addons/cellblender/cellblender_pa
nels.py:263
Traceback (most recent call last):
  File "/home/cellblender/.config/blender/2.71/scripts/addons/cellblender/cellblender_panels.py", line 171, in draw_item
    sp = cellblender.simulation_popen_list[index]
IndexError: list index out of range

location: 
/home/cellblender/.config/blender/2.71/scripts/addons/cellblender/cellblender_pa
nels.py:263

location: 
/home/cellblender/.config/blender/2.71/scripts/addons/cellblender/cellblender_pa
nels.py:263

```

Original issue reported on code.google.com by `cnlkucze...@gmail.com` on 6 Oct 2014 at 11:01

**Comment by jczech** [comment]
The new simulation runner does not use the simulation_popen_list, so this issue can be closed.

The remnants of the old simulation runners still need to be removed from the code base.
