### ISSUE TITLE
Running a new simulation while one is already running

### ISSUE THREAD

**Issue by jczech** [mcellteam/cellblender#81]
Using the new Queue based Simulation Runner, if you try to run a new simulation while one is already running, then you can trigger an error. Here is the traceback I received: 

```
Traceback (most recent call last):
  File "/home/jczech/.config/blender/2.74/scripts/addons/cellblender/cellblender_operators.py", line 1357, in execute
    bpy.ops.mcell.run_simulation_control_queue()
  File "/home/jczech/bin/blender_dir/blender-2.74-rc2-linux-glibc211-x86_64/2.74/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/home/jczech/.config/blender/2.74/scripts/addons/cellblender/cellblender_operators.py", line 1512, in execute
    shutil.rmtree(viz_dir)
  File "/home/jczech/bin/blender_dir/blender-2.74-rc2-linux-glibc211-x86_64/2.74/python/lib/python3.4/shutil.py", line 463, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/jczech/bin/blender_dir/blender-2.74-rc2-linux-glibc211-x86_64/2.74/python/lib/python3.4/shutil.py", line 405, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/home/jczech/bin/blender_dir/blender-2.74-rc2-linux-glibc211-x86_64/2.74/python/lib/python3.4/shutil.py", line 403, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'seed_00001'
```

**Comment by tmbartol** [comment]
Issue corrected in commit 3e1852f61baf30e26656bfa131f91dca3901ac19
