### ISSUE TITLE
Simulation runner bug

### ISSUE THREAD

**Issue by jczech** [mcellteam/cellblender#82]
This bug was reported by Annalisa Scimemi. It was triggered when using Blender 2.74, Cellblender 1.0, MCell 3.3, and Python 2.7. It is not entirely clear what is causing the problem, but it seems to be a problem with the new Queue based simulation runner. Here's an example traceback:

```
Traceback (most recent call last):
  File "/home/user/.config/blender/2.74/scripts/addons/cellblender/run_wrapper.py", line 20, in <module>
    proc = sp.Popen(cmd.split(), cwd=wd, bufsize=1, shell=False, stdout=sp.PIPE, stderr=sp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Task PID 26229 status: mcell_error return code: 1
Select Called without try/except with pin state:False, and old pin state = False
```

**Comment by tmbartol** [comment]
Issue fixed in commit c024a6a6b88e6ee7c753ff9650edcd56fcd6aaa3
